Repository F3B4-KDT-Project/front-end, pull requests merged in 2025-02, with the labels that each got.

#102 feat: auth api 연결
  src/apis/Auth/authApi.ts
  src/apis/axiosInstance.ts
  src/components/common/Input/index.tsx
  src/hooks/Auth/useSignIn.ts
  src/hooks/Auth/useSignUp.ts
  src/models/Auth.ts
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  vite.config.ts
Labels: ✨ FEAT

#104 refactor: 마이페이지 api 호출 함수 분리
  src/apis/Auth/myPageApi.ts
  src/hooks/Auth/useUpdateProfile.ts
  src/hooks/Auth/useUserProfile.ts
  src/pages/MyPage/index.tsx
Labels: ♻️ REFACTOR

#107 feat: 인증 보호된 라우트 적용
  src/App.tsx
  src/main.tsx
Labels: ✨ FEAT

#113 [feat] IDE 웹소켓 기능 구현 2 : 수신 기능 구현 중
  src/components/post/Chat/index.tsx
  src/components/post/Editor/IdeEditor.tsx
Labels: 🐛 FIX, ✨ FEAT

#112 feat / style : 게시판 생성 및 참여자 초대 api 연결
  src/apis/Board/createBoardApi.ts
  src/apis/Board/fetchBoardsApi.ts
  src/apis/Board/fetchPostsApi.ts
  src/apis/Board/inviteApi.ts
  src/components/layout/sideBar/index.tsx
  src/components/layout/sideBar/style.ts
  src/components/modals/AddBoardModal/index.tsx
  src/components/modals/InvitePersonModal/index.tsx
  src/hooks/Board/useBoardInvite.ts
  src/hooks/Board/useCreateBoard.ts
  src/hooks/Board/useFetchBoards.ts
  src/hooks/Board/useFetchPosts.ts
  src/models/Board.ts
  src/models/Modal.ts
  src/models/Post.ts
Labels: ✨ FEAT, 🔥 REMOVE, 🎨 STYLE

#116 [feat] IDE 웹소켓 실시간 구현 / 그 외 기능들 구현
  index.html
  src/components/post/Editor/IdeEditor.tsx
  src/models/Editor.type.ts
  src/pages/Post/index.tsx
  src/pages/Post/style.ts
Labels: 🐛 FIX, ✨ FEAT, 📝 DOCS

#118 feat: 게시글 네비게이션 추가 및 채팅 사용자 식별 오류 해결
  src/App.tsx
  src/apis/Chat/chatApi.ts
  src/apis/Posts/postApi.ts
  src/apis/postInstance.ts
  src/components/Post/Header/index.tsx
  src/components/Post/Header/style.ts
  src/components/board/Header.tsx
  src/components/board/Header/index.tsx
  src/components/board/Header/style.ts
  src/components/board/PostCard/index.tsx
  src/components/modals/AddPostModal/index.tsx
  src/components/post/Chat/index.tsx
  src/components/post/Header.tsx
  src/components/post/MessageCard/index.tsx
  src/hooks/Chat/useChatHistory.ts
  src/hooks/Posts/useCreatePost.ts
  src/hooks/Posts/useDeletePost.ts
  src/hooks/Posts/usePostDetail.ts
  src/hooks/Posts/usePosts.ts
  src/hooks/Posts/useUpdatePost.ts
  src/models/ChatData.type.ts
  src/models/Post.ts
  src/models/PostCard.ts
  src/pages/Board/index.tsx
  src/pages/Post/index.tsx
  src/pages/Post/style.ts
Labels: 🐛 FIX, ✨ FEAT

#121 style: 디자인 시스템 설정
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/board/Header.tsx
  src/components/board/Header/index.tsx
  src/components/board/Header/style.ts
  src/components/board/PostCard/style.ts
  src/components/board/UserInfo/style.ts
  src/components/common/Input/style.ts
  src/components/layout/sideBar/style.ts
  src/components/modals/AddBoardModal/index.tsx
  src/components/modals/AddBoardModal/style.ts
  src/components/modals/AddPostModal/index.tsx
  src/components/modals/AddPostModal/style.ts
  src/components/modals/DeleteBoardModal/index.tsx
  src/components/modals/DeleteBoardModal/style.ts
  src/components/modals/DeletePostModal/index.tsx
  src/components/modals/DeletePostModal/style.ts
  src/components/modals/EditBoardModal/index.tsx
  src/components/modals/EditBoardModal/style.ts
  src/components/modals/EditPostModal/index.tsx
  src/components/modals/EditPostModal/style.ts
  src/components/modals/InvitePersonModal/index.tsx
  src/components/modals/InvitePersonModal/style.ts
  src/components/myPage/ProfileDetails/index.tsx
  src/components/myPage/ProfileDetails/style.ts
  src/components/myPage/ProfileImage/index.tsx
  src/components/myPage/ProfileImage/style.ts
  src/components/myPage/ThemeSelection/index.tsx
  src/components/myPage/ThemeSelection/style.ts
  src/components/post/Chat/style.ts
  src/components/post/Editor/IdeEditor.tsx
  src/components/post/Editor/index.tsx
  src/components/post/Editor/style.ts
  src/components/post/Header.tsx
  src/components/post/Header/index.tsx
  src/components/post/Header/style.ts
  src/components/post/MessageCard/index.tsx
  src/components/post/MessageCard/style.ts
  src/index.css
  src/main.tsx
  src/models/MyPage.ts
  src/pages/Board/index.tsx
  src/pages/Board/style.ts
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
  src/pages/Post/index.tsx
  src/pages/Post/style.ts
  src/reset.css
  src/styles/GlobalStyle.tsx
  src/styles/fonts.ts
  src/styles/theme.ts
Labels: ♻️ REFACTOR

#123 fix : IDE websocket 수신 해결중
  src/components/post/Editor/index.tsx
  src/hooks/Post/useIdeWebsocket.ts
Labels: 🐛 FIX

#125 [fix] 로그인 오류 임시 해결 및 라우터 기능 복원
  src/App.tsx
  src/apis/Auth/authApi.ts
  src/apis/Chat/chatApi.ts
  src/apis/Posts/postApi.ts
  src/apis/axiosInstance.ts
  src/apis/postInstance.ts
  src/components/board/Header/index.tsx
  src/components/board/Header/style.ts
  src/components/board/PostCard/index.tsx
  src/components/modals/AddPostModal/index.tsx
  src/components/post/Chat/index.tsx
  src/components/post/Editor/index.tsx
  src/components/post/Header/index.tsx
  src/components/post/Header/style.ts
  src/components/post/MessageCard/index.tsx
  src/hooks/Chat/useChatHistory.ts
  src/hooks/Chat/useIdeWebsocket.ts
  src/hooks/Post/useIdeWebsocket.ts
  src/hooks/Posts/useCreatePost.ts
  src/hooks/Posts/useDeletePost.ts
  src/hooks/Posts/usePostDetail.ts
  src/hooks/Posts/usePosts.ts
  src/hooks/Posts/useUpdatePost.ts
  src/models/ChatData.type.ts
  src/models/Post.ts
  src/models/PostCard.ts
  src/pages/Board/index.tsx
  src/pages/Post/index.tsx
Labels: 🐛 FIX, ✨ FEAT

#129 feat: 캘린더 컴포넌트 UI 개발 및 스타일
  src/components/board/Calendar/index.tsx
  src/components/board/Calendar/style.ts
  src/components/board/TaskCard/index.tsx
  src/components/board/TaskCard/style.ts
  src/models/Calendar.ts
Labels: ✨ FEAT, 🎨 STYLE

#131 feat: 캘린더 기능 구현
  package-lock.json
  package.json
  src/components/board/Calendar/index.tsx
  src/components/board/Calendar/style.ts
Labels: ✨ FEAT, 🎨 STYLE, 💬 CHORE

#132 [ feat ] Post 페이지 api 연동 시도 중, IDE api 연동 시도 중
  src/apis/Ide/ideApi.ts
  src/apis/Ide/useIdeWebsocket.ts
  src/apis/Posts/postApi.ts
  src/components/post/Editor/index.tsx
  src/models/Editor.type.ts
  src/models/Ide.ts
  src/models/Post.ts
  src/pages/Post/index.tsx
Labels: 📝 DOCS, ✅ TEST

#135 fix : Post 관련 빌드 에러 해결
  src/hooks/Posts/useCreatePost.ts
  src/hooks/Posts/usePostDetail.ts
  src/hooks/Posts/usePosts.ts
  src/pages/Post/index.tsx
Labels: 🐛 FIX

#140 feat: 로그인 페이지 컴포넌트 분리
  src/components/login/ButtonSection/index.tsx
  src/components/login/ButtonSection/style.ts
  src/components/login/Header/index.tsx
  src/components/login/Header/style.ts
  src/pages/Login/index.tsx
  src/pages/Login/style.ts
Labels: ♻️ REFACTOR

#142 feat: 카카오 로그인 구현
  src/App.tsx
  src/apis/Auth/authApi.ts
  src/components/login/ButtonSection/index.tsx
  src/hooks/Auth/useLogIn.ts
  src/hooks/Auth/useSignUp.ts
  src/models/Auth.ts
  src/pages/Login/KakaoCallback.tsx
Labels: ✨ FEAT

#143 refactor: Interface 이름 통일
  src/apis/Auth/authApi.ts
  src/hooks/Auth/useLogIn.ts
  src/models/Auth.ts
Labels: ♻️ REFACTOR

#149 feat: 마이페이지 2차 추가 기능 개발
  package-lock.json
  package.json
  src/App.tsx
  src/apis/Auth/myPageApi.ts
  src/assets/icons/notification_item.svg
  src/components/myPage/Input/index.tsx
  src/components/myPage/Notification/Item/index.tsx
  src/components/myPage/Notification/Item/style.ts
  src/components/myPage/Notification/index.tsx
  src/components/myPage/Notification/style.ts
  src/components/myPage/ProfileDetails/index.tsx
  src/components/myPage/ProfileDetails/style.ts
  src/hooks/Auth/useUpdateProfile.ts
  src/models/Auth.ts
  src/models/Common.ts
  src/models/MyPage.ts
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
Labels: ✨ FEAT, ♻️ REFACTOR, 🎨 STYLE

#151 feat: sideBar 개선
  src/components/layout/sideBar/index.tsx
  src/components/layout/style.ts
Labels: ✨ FEAT, 🎨 STYLE

#154 feat: 알림 api 연결
  src/apis/Notifications/inviteDecisionApi.ts
  src/apis/Notifications/notificationApi.ts
  src/components/modals/InvitationDecisionModal/index.tsx
  src/components/modals/InvitationDecisionModal/style.ts
  src/components/modals/InviteAcceptModal/index.tsx
  src/components/modals/InviteRejectModal/index.tsx
  src/components/modals/InviteRejectModal/style.ts
  src/components/myPage/Notification/Item/index.tsx
  src/components/myPage/Notification/Item/style.ts
  src/components/myPage/Notification/index.tsx
  src/components/myPage/Notification/style.ts
  src/hooks/Notifications/useAcceptInvitation.ts
  src/hooks/Notifications/useNotifications.ts
  src/hooks/Notifications/useRejectInvitation.ts
  src/models/Modal.ts
  src/models/MyPage.ts
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
  src/styles/theme.ts
Labels: ✨ FEAT

#161 feat: 캘린더 기능 api 연동
  src/apis/Board/calenderApi.ts
  src/components/board/Calendar/index.tsx
  src/components/board/Calendar/style.ts
  src/components/board/TaskCard/index.tsx
  src/hooks/Board/useFetchScheduleList.ts
  src/models/Calendar.ts
Labels: ✨ FEAT

#168 style: 알림 스타일 수정
  src/components/myPage/Notification/Item/index.tsx
  src/components/myPage/Notification/Item/style.ts
  src/components/myPage/Notification/style.ts
Labels: 🎨 STYLE

#170 fix: 한글 채팅 시 마지막 글자 중복 출력 오류 해결
  src/components/post/Chat/index.tsx
Labels: 🐛 FIX

#173 fix: 마이페이지 프로필 이미지 처리 로직 수정
  src/components/myPage/ProfileImage/index.tsx
Labels: 🐛 FIX

#176 refactor: 닉네임 수정 후 refetch 방법 queryKey 사용으로 변경
  src/pages/MyPage/index.tsx
Labels: ♻️ REFACTOR

#180 feat: 캘린더 게시판 연결
  src/pages/Board/index.tsx
  src/pages/Board/style.ts
Labels: ✨ FEAT, 🎨 STYLE

#186 fix: sideBar 라우터 오류 해결
  src/App.tsx
  src/components/layout/sideBar/index.tsx
  src/pages/Board/index.tsx
Labels: 🐛 FIX
