Repository F3B4-KDT-Project/front-end, pull requests merged in 2025-01, with the labels that each got.

#3 Chore: 프로젝트 생성 및 설정
  .eslintrc.js
  .gitignore
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/icons/.gitkeep
  src/assets/react.svg
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/index.css
  src/main.tsx
  src/models/.gitkeep
  src/pages/.gitkeep
  src/stores/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  types/.gitkeep
  vite.config.ts
Labels: 💬 CHORE

#4 feat: 프로젝트 초기 설정
  src/App.css
  src/App.tsx
  src/index.css
  src/main.tsx
  src/pages/.gitkeep
  src/pages/Board/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/Post/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
Labels: ✨ FEAT

#6 chore: 파비콘 및 페이지 타이틀 설정
  index.html
  src/assets/icons/.gitkeep
  src/assets/icons/logo_black.svg
  src/assets/icons/logo_white.svg
  src/assets/react.svg
Labels: 💬 CHORE

#9 chore: 패키지 추가 설치 / feat: 초기 설정 추가
  package-lock.json
  package.json
  src/App.css
  src/index.css
  src/reset.css
Labels: ✨ FEAT, 💬 CHORE

#11 chore: react-query 설치 및 설정
  package-lock.json
  package.json
  src/main.tsx
Labels: ✨ FEAT, 💬 CHORE

#13 chore: lint-staged 설정에 test 스크립트 추가
  package.json
Labels: 💬 CHORE

#17 feat: 로그인&회원가입 공통 컴포넌트 개발
  src/components/auth/Button/index.tsx
  src/components/auth/Input/index.tsx
  types/Auth.ts
Labels: ✨ FEAT

#23 style: 로그인&회원가입 공통 컴포넌트 스타일링
  src/components/auth/Button/index.tsx
  src/components/auth/Button/style.ts
  src/components/auth/Input/index.tsx
  src/components/auth/Input/style.ts
Labels: 🎨 STYLE

#25 rename: input 컴포넌트 이름 변경 및 파일 위치 수정
  src/components/auth/Button/index.tsx
  src/components/auth/Button/style.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  types/.gitkeep
  types/Auth.ts
  types/Common.ts
Labels: ♻️ REFACTOR, ✍🏻 RENAME

#26 rename: input 컴포넌트 이름 변경 및 파일 위치 수정
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  types/.gitkeep
  types/Auth.ts
  types/Common.ts
Labels: ♻️ REFACTOR, ✍🏻 RENAME

#28 feat: 로그인 화면 설계
  src/components/common/Input/index.tsx
  src/pages/SignIn/index.tsx
Labels: ✨ FEAT

#33 chore: pretendard 폰트 파일 추가
  src/assets/fonts/Pretendard-Medium.woff2
Labels: 💬 CHORE

#29 chore: 추가 패키지 설치 / feat: 채팅 컴포넌트 화면 설계 및 스타일링
  package.json
  src/components/Post/Chat/index.tsx
  src/components/Post/Chat/style.ts
  src/components/Post/MessageCard/index.tsx
  src/components/Post/MessageCard/style.ts
  src/models/ChatData.type.ts
  src/pages/Post/index.tsx
Labels: ✨ FEAT, 🎨 STYLE, 💬 CHORE

#38 fix: 채팅 컴포넌트 React import 추가
  src/components/Post/Chat/index.tsx
  src/components/Post/MessageCard/index.tsx
Labels: 🐛 FIX

#41 chore: 상수화 설정 수정
  src/index.css
Labels: 💬 CHORE

#44 style: css 컬러명 수정
  src/components/auth/Button/style.ts
  src/components/common/Input/style.ts
  src/pages/SignIn/style.ts
Labels: 🎨 STYLE

#50 chore : 이름 수정, import 변수 삭제, react import 추가, props 설정, userID 임시 함수 선언
  src/App.tsx
  src/components/Post/Editor/IdeEditor.tsx
  src/components/Post/Editor/index.tsx
  src/components/Post/Header.tsx
  src/components/Post/MessageCard/index.tsx
  src/main.tsx
  src/pages/Board/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/Post/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  vite.config.ts
Labels: 📝 DOCS, 💬 CHORE

#51 chore: eslint-config-prettier 패키지 삭제
  .eslintrc.js
  package-lock.json
  package.json
Labels: 💬 CHORE

#54 feat: 채팅 컴포넌트 줄바꿈 기능 추가 및 컴포넌트 결합
  package-lock.json
  src/components/Post/Chat/index.tsx
  src/components/Post/Chat/style.ts
  src/components/Post/MessageCard/style.ts
  src/pages/Post/index.tsx
Labels: ✨ FEAT

#56 style : IDE theme 적용 / props 설정 / 더미데이터 및 테스트 코드 작성
  public/monaco-themes/Tomorrow.json
  public/monaco-themes/dark.json
  public/monaco-themes/light.json
  src/assets/editor/dark.json
  src/assets/editor/light.json
  src/components/Post/Editor/IdeEditor.tsx
  src/components/Post/Header.tsx
  src/pages/Post/index.tsx
Labels: ✨ FEAT, 📝 DOCS, 🔥 REMOVE

#59 style: 시멘틱 요소 수정
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/components/layout/style.ts
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style.ts
Labels: 🎨 STYLE

#57 feat: 회원가입 화면 레이아웃 구성
  src/pages/SignUp/index.tsx
Labels: ✨ FEAT

#64 style: 회원가입 페이지 퍼블리싱
  src/components/auth/Button/style.ts
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.ts
Labels: 🎨 STYLE

#66 chore: 컬러 상수 선언 최적화
  src/index.css
Labels: 💬 CHORE

#68 feat: 마이페이지 UI 구현
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
Labels: ✨ FEAT, 🎨 STYLE

#71 style: css 속성 수정
  src/pages/MyPage/style.ts
Labels: 🔥 REMOVE, 🎨 STYLE

#73 feat : Editor 코드 복사, 저장(api 작업 필요), 커스텀 테마 구현
  public/monaco-themes/dark.json
  src/components/Post/Editor/IdeEditor.tsx
  src/pages/Post/index.tsx
Labels: ✨ FEAT, 📝 DOCS, 🔥 REMOVE, 🎨 STYLE

#74 style: Input 컴포넌트 길이 스타일 수정
  src/components/common/Input/style.ts
  src/pages/MyPage/style.ts
  src/pages/SignIn/style.ts
  src/pages/SignUp/style.ts
Labels: 🎨 STYLE

#77 rename: post 폴더명 수정
  package-lock.json
Labels: ✍🏻 RENAME

#78 feat: api 연결 전 초기 설정
  src/apis/axiosInstance.ts
  src/apis/httpClient.ts
  src/apis/queryClient.ts
  src/main.tsx
Labels: ✨ FEAT

#80 [feat] Editor 코드 하이라이터 기능 구현 / 웹소켓 통신 작업 시도 1
  package-lock.json
  package.json
  src/components/Post/Editor/IdeEditor.tsx
  src/components/Post/Editor/style.ts
  src/models/Editor.type.ts
Labels: ✨ FEAT, 📝 DOCS, 🔥 REMOVE, 💬 CHORE

#82 feat / style : 게시판 페이지 ui 작업, 사이드바 height 수정, 게시글 컴포넌트&게시판 생성 모달 추가
  package-lock.json
  src/App.tsx
  src/assets/icons/addbtn_dark.svg
  src/assets/icons/addbtn_light.svg
  src/assets/icons/profilebtn.svg
  src/components/Post/MessageCard/index.tsx
  src/components/board/Header.tsx
  src/components/board/PostCard/index.tsx
  src/components/board/PostCard/style.ts
  src/components/layout/sideBar/index.tsx
  src/components/layout/sideBar/style.ts
  src/components/layout/style.ts
  src/components/modals/AddBoardModal/index.tsx
  src/components/modals/AddBoardModal/style.ts
  src/index.css
  src/models/PostCard.ts
  src/pages/Board/index.tsx
  src/pages/Board/style.ts
Labels: ✨ FEAT, 📝 DOCS, 🔥 REMOVE, 🎨 STYLE

#81 feat: 채팅 메세지 채팅 사용자에 따라 구분 기능 추가
  src/components/Post/Chat/index.tsx
  src/components/Post/Chat/style.ts
  src/components/Post/MessageCard/index.tsx
  src/components/Post/MessageCard/style.ts
  src/models/ChatData.type.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#86 feat: 마이페이지 api 연결
  src/apis/axiosInstance.ts
  src/apis/queryClient.ts
  src/hooks/.gitkeep
  src/hooks/Auth/useUpdateProfile.ts
  src/hooks/Auth/useUserProfile.ts
  src/models/Auth.ts
  src/pages/MyPage/index.tsx
Labels: ✨ FEAT

#87 feat: 채팅 websocket 실시간 통신 구현
  package-lock.json
  src/components/Post/Chat/index.tsx
  src/components/Post/Chat/style.ts
  src/components/Post/MessageCard/index.tsx
  src/components/Post/MessageCard/style.ts
  src/models/ChatData.type.ts
  src/vite-env.d.ts
Labels: ✨ FEAT, 💬 CHORE

#89 [feat] ide websocket 통신
  src/apis/postInstance.ts
  src/components/Post/Editor/IdeEditor.tsx
  src/components/Post/Header.tsx
  src/models/PostHeader.type.ts
  src/pages/Post/index.tsx
Labels: ✨ FEAT, 📝 DOCS, ✅ TEST

#91 feat / style : 남은 모달창 ui 및 기능 구현 작업
  src/components/Post/Header.tsx
  src/components/board/Header.tsx
  src/components/board/UserInfo/index.tsx
  src/components/board/UserInfo/style.ts
  src/components/modals/AddPostModal/index.tsx
  src/components/modals/AddPostModal/style.ts
  src/components/modals/DeletePostModal/index.tsx
  src/components/modals/DeletePostModal/style.ts
  src/components/modals/EditPostModal/index.tsx
  src/components/modals/EditPostModal/style.ts
  src/components/modals/InvitePersonModal/index.tsx
  src/components/modals/InvitePersonModal/style.ts
  src/index.css
  src/models/PostCard.ts
  src/pages/Board/index.tsx
Labels: ✨ FEAT, 🎨 STYLE

#94 style : 모달창 placeholder 색상 변경
  src/components/modals/AddBoardModal/style.ts
  src/components/modals/AddPostModal/style.ts
  src/components/modals/EditBoardModal/style.ts
  src/components/modals/EditPostModal/style.ts
  src/components/modals/InvitePersonModal/style.ts
Labels: 🎨 STYLE

#96 refactor: 마이페이지 컴포넌트화
  package-lock.json
  public/vite.svg
  src/components/myPage/ProfileDetails/index.tsx
  src/components/myPage/ProfileDetails/style.ts
  src/components/myPage/ProfileImage/index.tsx
  src/components/myPage/ProfileImage/style.ts
  src/components/myPage/ThemeSelection/index.tsx
  src/components/myPage/ThemeSelection/style.ts
  src/models/MyPage.ts
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
Labels: ♻️ REFACTOR

#98 feat: 테마 변경 기능 구현
  src/components/myPage/ThemeSelection/index.tsx
Labels: ✨ FEAT

#100 Feat: 다른 페이지로 이동해도 테마 변경 유지되게 추가
  src/App.tsx
  src/components/myPage/ThemeSelection/index.tsx
  src/models/MyPage.ts
  src/pages/MyPage/index.tsx
Labels: ✨ FEAT
